### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by martin-ro** [rabol/filament-logviewer#2]

**Comment by rabol** [comment]
The required jackiedo/log-reader package does not yet support L9

**Comment by Simoneu01** [comment]
it does support now:
https://github.com/JackieDo/Laravel-Log-Reader/issues/37

https://github.com/JackieDo/Laravel-Log-Reader/releases/tag/2.2.1

**Comment by rabol** [comment]
Updated to support laravel 9
