### ISSUE TITLE
could not find driver (SQL: create table "log_files" ("id" integer not null primary key autoincrement,

### ISSUE THREAD

**Issue by djoudi** [rabol/filament-logviewer#4]
Illuminate\Database\QueryException
could not find driver (SQL: create table "log_files" ("id" integer not null primary key autoincrement, "name" varchar, "path" varchar))

![image](https://user-images.githubusercontent.com/152725/169955782-e997fef1-8a36-4a28-92b2-1a74cf97c193.png)

**Comment by ak-flash** [comment]
You need to install PDO on your server, or you might have to just comment out the following line in your php.ini file.

```
;extension=pdo_sqlite
;extension=sqlite3
```
(remove the ; character)

You should then restart your server.
